### PR TITLE
fix for issue-18

### PR DESCRIPTION
**Pull request by omosun**
fix for mysql
#18

### CODE REVIEW

**Comment by SIkebe** [comment]
@omosun I can't see your icon here.
image

Is the email address associated with the commit correct?

**Review by SIkebe — APPROVED** [review]

**Comment by SIkebe** [comment]
Hi @omosun ,
Is that OK if I merge this PR as is?

**Comment by alexandremenif** [comment]
@SIkebe @omosun in my opinion we should do the following changes before being able to merge this:
- target the develop branch instead of master
- implement the change in a new changeset file, the existing ones should not be modified

**Comment by SIkebe** [comment]
@alexandremenif Thanks! I know this repo follows git flow, and the commit in the "omosun:master" branch should not be merged into this repo as is (because of the e-mail thing I mentioned above).
So I'm going to create new commit in a different branch, and merge by myself.

**Comment by SIkebe** [comment]
@alexandremenif Could you change default branch from master to develop? Every time we create a new PR it defaults to master, and we often forget to re-target base branch to develop instead of master 😂

**Comment by SIkebe** [comment]
#26

**Pull request closed without merging**
