### PR TITLE
Bump to GItBucket 4.32.0

### PR DESCRIPTION
**Pull request by SIkebe**
* scala 2.13.0
* GitBucket 4.32.0
* sbt 1.2.8

### CODE REVIEW

**Comment by alexandremenif** [comment]
Hello @SIkebe. Thank you for your pull request. The code looks good to me, but I have not used Gitbucket for a while and lack the time to go back to it and test the pull request. Would you be interested in maintaining this project ? If so I would make you a collaborator and let you merge this PR and do the release.

**Comment by SIkebe** [comment]
@alexandremenif Thank you for your proposal. That would be great!

**Comment by SIkebe** [comment]
@alexandremenif Thank you for inviting me as a collaborator! Much appreciated.
Before merge & release, let me know about the branch strategy.
This repo has master and develop branch. Are you using git-flow? If yes, then should change the base branch to develop?

**Comment by alexandremenif** [comment]
> @alexandremenif Thank you for inviting me as a collaborator! Much appreciated.
> Before merge & release, let me know about the branch strategy.
> This repo has master and develop branch. Are you using git-flow? If yes, then should change the base branch to develop?

@SIkebe I was more or less applying git-flow. New features are first merged to develop, then they get merged in master when doing a release. So indeed it would be better to target develop here. I do not think that I was using git-flow to make the release, since there is no release branch left. Maybe we could start doing it for the next one.

**Comment by SIkebe** [comment]
>Maybe we could start doing it for the next one.

OK, I'm going to go ahead and merge this one, then.

**Pull request merged**
